# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.4.0"
threads = 8
stack-size = 8388608 # 8 MB
editor-url = "phpstorm://open?file=%file%&line=%line%&column=%column%"

[source]
workspace = "."
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

# Contao specific rules
#no-global = {enabled = false}
#no-boolean-flag-parameter = {enabled = false}
#too-many-properties = {enabled = false}
#too-many-methods = {enabled = false}

[analyzer]
# Enable all checks
find-unused-expressions = true
find-unused-definitions = true
analyze-dead-code = true
check-throws = true
check-missing-override = true
find-unused-parameters = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true
enforce-class-finality = true
require-api-or-internal = true

# Enable strict checks
strict-list-index-checks = true
no-boolean-literal-comparison = true

# Disable lenient behaviors
trust-existence-checks = false

## Project specific rules

# PHPUnit assertions may throw framework exceptions; treat them as unchecked in static throw analysis.
unchecked-exceptions = ["PHPUnit\\Framework\\Exception"]

# The Contao DCA uses this a lot, so we allow that
allow-possibly-undefined-array-keys = true
